# Generated by Django 4.2.4 on 2023-08-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='club',
        ),
        migrations.DeleteModel(
            name='match',
        ),
        migrations.DeleteModel(
            name='member',
        ),
        migrations.DeleteModel(
            name='player',
        ),
        migrations.DeleteModel(
            name='tournament',
        ),
    ]
