# Generated by Django 4.2.4 on 2023-08-21 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0004_delete_club_delete_match_delete_member_delete_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.member')),
            ],
        ),
        migrations.CreateModel(
            name='tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('player', models.ManyToManyField(to='club.player')),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('play_date_time', models.DateTimeField()),
                ('player_one_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_id_set', to='club.player')),
                ('player_two_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_two_set', to='club.player')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.tournament')),
                ('winner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_id_set', to='club.player')),
            ],
        ),
    ]
