# Generated by Django 4.2.4 on 2023-08-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='match',
        ),
    ]
